// packages/shared/src/constants/business-rules.constants.ts

// Import domain-specific business rules to aggregate them
import { PAYMENT_BUSINESS_RULES } from './payment.constants';
import { APPOINTMENT_BUSINESS_RULES } from './appointment.constants';
import { FILE_BUSINESS_RULES } from './file.constants';
import { NOTIFICATION_BUSINESS_RULES } from './notification.constants';
import { SYSTEM_BUSINESS_RULES } from './system.constants';

// Cross-domain business rules that don't belong to a specific domain
export const BUSINESS_RULES = {
  // Authentication & Security
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 128,
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MINUTES: 30,
  SESSION_TIMEOUT_MINUTES: SYSTEM_BUSINESS_RULES.SESSION_TIMEOUT_MINUTES,
  PASSWORD_EXPIRY_DAYS: 90,
  TWO_FACTOR_CODE_LENGTH: 6,
  TWO_FACTOR_EXPIRY_MINUTES: 10,
  BCRYPT_ROUNDS: SYSTEM_BUSINESS_RULES.BCRYPT_ROUNDS,
  
  // User Management
  MIN_AGE_YEARS: 18,
  MAX_AGE_YEARS: 120,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 30,
  
  // Case Management
  CASE_NUMBER_PREFIX: 'CASE',
  CASE_NUMBER_LENGTH: 8,
  AUTO_ARCHIVE_DAYS: 90,
  MIN_CASE_FILES: FILE_BUSINESS_RULES.MIN_CASE_FILES,
  MAX_CASE_FILES: 50,
  CASE_RETENTION_YEARS: 7,
  
  // Appointments (reference domain-specific rules)
  MIN_APPOINTMENT_DURATION: APPOINTMENT_BUSINESS_RULES.MIN_APPOINTMENT_DURATION,
  MAX_APPOINTMENT_DURATION: APPOINTMENT_BUSINESS_RULES.MAX_APPOINTMENT_DURATION,
  DEFAULT_APPOINTMENT_DURATION_MINUTES: APPOINTMENT_BUSINESS_RULES.DEFAULT_APPOINTMENT_DURATION,
  APPOINTMENT_REMINDER_DAYS: APPOINTMENT_BUSINESS_RULES.APPOINTMENT_REMINDER_DAYS,
  APPOINTMENT_BUFFER_MINUTES: APPOINTMENT_BUSINESS_RULES.APPOINTMENT_BUFFER_MINUTES,
  
  // Payments (reference domain-specific rules)
  PAYMENT_OVERDUE_DAYS: PAYMENT_BUSINESS_RULES.PAYMENT_OVERDUE_DAYS,
  DEFAULT_CURRENCY: PAYMENT_BUSINESS_RULES.DEFAULT_CURRENCY,
  MAX_PAYMENT_AMOUNT: PAYMENT_BUSINESS_RULES.MAX_PAYMENT_AMOUNT,
  MIN_PAYMENT_AMOUNT: PAYMENT_BUSINESS_RULES.MIN_PAYMENT_AMOUNT,
  
  // Files (reference domain-specific rules)
  MAX_FILE_SIZE_MB: FILE_BUSINESS_RULES.MAX_FILE_SIZE_MB,
  MAX_TOTAL_STORAGE_GB: 10,
  
  // System Defaults (reference domain-specific rules)
  DEFAULT_LANGUAGE: SYSTEM_BUSINESS_RULES.DEFAULT_LANGUAGE,
  DEFAULT_TIMEZONE: SYSTEM_BUSINESS_RULES.DEFAULT_TIMEZONE,
  DEFAULT_DATE_FORMAT: SYSTEM_BUSINESS_RULES.DEFAULT_DATE_FORMAT,
  DEFAULT_TIME_FORMAT: SYSTEM_BUSINESS_RULES.DEFAULT_TIME_FORMAT,
  
  // Pagination
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  
  // Performance
  CACHE_TTL_SECONDS: 300,
  API_TIMEOUT_SECONDS: 30,
  
  // Business Hours
  BUSINESS_HOURS_START: '08:00',
  BUSINESS_HOURS_END: '18:00',
  BUSINESS_DAYS: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
  
  // Notifications (reference domain-specific rules)
  MAX_NOTIFICATIONS_PER_USER: 1000,
  NOTIFICATION_RETENTION_DAYS: NOTIFICATION_BUSINESS_RULES.NOTIFICATION_RETENTION_DAYS,
  
  // Export/Import
  MAX_EXPORT_ROWS: SYSTEM_BUSINESS_RULES.MAX_EXPORT_ROWS,
  MAX_IMPORT_FILE_SIZE_MB: 50,
  
  // Email
  MAX_EMAIL_RECIPIENTS: 50,
  EMAIL_RATE_LIMIT_PER_HOUR: 100,
  
  // SMS
  MAX_SMS_LENGTH: 160,
  SMS_RATE_LIMIT_PER_HOUR: 50
} as const;

export type BusinessRuleKey = keyof typeof BUSINESS_RULES;
export type BusinessRuleValue = typeof BUSINESS_RULES[BusinessRuleKey];