import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "../components/AuthSessionProvider";
import { Toaster } from "react-hot-toast"; // <-- ADD THIS IMPORT

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AuthSessionProvider>
                    {/* Toast notifications for the whole app */}
                    <Toaster position="top-right" reverseOrder={false} />
                    {children}
                </AuthSessionProvider>
            </body>
        </html>
    );
}